config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root

      resources :tutors do
		      collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { get :export}

	    end

      resources :groups do
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { post :add_student}
          collection { delete :delete_student}
          collection { get :export}

          collection { delete :remove_students}
          collection { post :add_many_students}
	    end

      resources :supervisors do
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { post :import }
	    end

      resources :stakeholders do
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { post :import }
	    end

      resources :coordinators do
          collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}

	    end

      resources :students do
		      collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { get :export}
	    end

      resources :courses do
		      collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { get :export}

	    end

      get "/logout" => "devise/sessions#destroy"
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
      get "/login" => "devise/sessions#new"
    end
  end
end

app/models/supervisor.rb
class Supervisor < ApplicationRecord
  has_many :groups, dependent: :destroy

  def self.import(file)

    all_supervisors = []
    Supervisor.all.each do |supervisor|
      all_supervisors.push(supervisor.username)
    end

    xlsx = Roo::Spreadsheet.open(file.path)
    xlsx.drop(1).each do |row|

      username = row[0]

      if !all_supervisors.include?(username)
          Supervisor.create(
            username: row[0],
            internal_password: row[1],
            name: row[2],
            first_last_name: row[3],
            second_last_name: row[4],
            email: row[5],
            country: row[6],
            state: row[7],
            city: row[8],
            partner: row[9],
            organization_code: row[10]
          )

          all_supervisors.push(username)

      end

    end

  end

end

app/controllers/supervisors_controller.rb
class SupervisorsController < ApplicationController
  before_action :set_supervisor, only: [:show, :edit, :update, :destroy]

  # GET /supervisors
  # GET /supervisors.json
  def index
    if params[:search]
      @supervisors = Supervisor.where('name ILIKE ?', "%#{params[:search]}%").order("username ASC")
    else
      @supervisors = Supervisor.order("username ASC")
    end
  end

  # GET /supervisors/1
  # GET /supervisors/1.json
  def show
  end

  # GET /supervisors/new
  def new
    @supervisor = Supervisor.new
  end

  def import
   Supervisor.import(params[:file])
   redirect_to supervisors_path
  end

  # GET /supervisors/1/edit
  def edit
  end

  # POST /supervisors
  # POST /supervisors.json
  def create
    @supervisor = Supervisor.new(supervisor_params)

    respond_to do |format|
      if @supervisor.save
        format.html { redirect_to @supervisor, notice: 'Supervisor was successfully created.' }
        format.json { render :show, status: :created, location: @supervisor }
      else
        format.html { render :new }
        format.json { render json: @supervisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /supervisors/1
  # PATCH/PUT /supervisors/1.json
  def update
    respond_to do |format|
      if @supervisor.update(supervisor_params)
        format.html { redirect_to @supervisor, notice: 'Supervisor was successfully updated.' }
        format.json { render :show, status: :ok, location: @supervisor }
      else
        format.html { render :edit }
        format.json { render json: @supervisor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /supervisors/1
  # DELETE /supervisors/1.json
  def destroy
    @supervisor.destroy
    respond_to do |format|
      format.html { redirect_to supervisors_url, notice: 'Supervisor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_multiple

    if params[:supervisor_ids]
      Supervisor.destroy(params[:supervisor_ids])
      message = {notice: 'Borrado con éxito.'}
    else
      message = {alert: 'Por favor selecciona al menos uno.'}
    end

    respond_to do |format|
      format.html { redirect_to supervisors_url }
      format.json { head :no_content }
    end
  end

  def destroy_all
    Supervisor.all.each do  |supervisor|
      supervisor.destroy
    end

    redirect_to supervisors_path, notice: "Borrados Exitosamente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supervisor
      @supervisor = Supervisor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supervisor_params
      params.require(:supervisor).permit(:username, :internal_password, :name, :first_last_name, :second_last_name, :email, :country, :state, :city, :partner, :organization_code, :gender, :dob, :phone_number, :language)
    end
end

app/helpers/supervisors_helper.rb
module SupervisorsHelper
end

app/views/supervisors/_form.html.erb
      <%= form_with(model: supervisor, local: true) do |form| %>
      <% if supervisor.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(supervisor.errors.count, "error") %> prohibited this supervisor from being saved:</h2>

        <ul>
          <% supervisor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div class="field">
        <%= form.label :username, 'Nombre de usuario' %>
        <%= form.text_field :username %>
      </div>

      <div class="field">
        <%= form.label :internal_password, 'Contraseña' %>
        <%= form.text_field :internal_password %>
      </div>

      <div class="field">
        <%= form.label :name, 'Nombre' %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :first_last_name, 'Apellido paterno' %>
        <%= form.text_field :first_last_name %>
      </div>

      <div class="field">
        <%= form.label :second_last_name, 'Apellido materno' %>
        <%= form.text_field :second_last_name %>
      </div>

      <div class="field">
        <%= form.label :email, 'Correo electrónico' %>
        <%= form.text_field :email %>
      </div>

      <div class="field">
        <%= form.label :country, 'País' %>
        <%= form.text_field :country %>
      </div>

      <div class="field">
        <%= form.label :state, 'Estado' %>
        <%= form.text_field :state %>
      </div>

      <div class="field">
        <%= form.label :city, 'Ciudad' %>
        <%= form.text_field :city %>
      </div>

      <div class="field">
        <%= form.label :partner, 'Socio' %>
        <%= form.text_field :partner %>
      </div>

      <div class="field">
        <%= form.label :organization_code, 'Código de organización' %>
        <%= form.text_field :organization_code %>
      </div>

      <div class="field">
        <%= form.label :gender, 'Género' %>
        <%= form.number_field :gender %>
      </div>

      <div class="field">
        <%= form.label :dob, 'Fecha de nacimiento' %>
        <%= form.date_select :dob, start_year: 1900 %>
      </div>

      <div class="field">
        <%= form.label :phone_number, 'Número telefónico' %>
        <%= form.text_field :phone_number %>
      </div>

      <div class="field">
        <%= form.label :language, 'Idioma' %>
        <%= form.text_field :language %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/supervisors/edit.html.erb
<div class="content-container footer-container">
  <div class="container-fluid">
    <div class="jumbotron" >

      <h1>Editar Supervisor</h1>

      <%= render 'form', supervisor: @supervisor %>

      <%= link_to 'Ver', @supervisor %> |
      <%= link_to 'Atrás', supervisors_path %>
    </div>
  </div>
</div>

app/views/supervisors/index.html.erb
<div class="content-container footer-container">
  <div class="container-fluid">
    <div class="jumbotron" >

      <h1>Supervisores</h1>

      <div class="md-form mt-0">
        <%= form_tag(supervisors_path, method: :get) do %>
          <%= text_field_tag :search,"", class: "form-control", placeholder: "Busqueda" %>
        <% end %>
      </div><br>

      <%= form_tag destroy_multiple_supervisors_path, method: :delete do %>
      <div class="scroll">
        <table class="table table-hover table-fixed course_header">
          <!--Table head-->
          <thead >
            <tr>
              <th>Nombre de usuario</th>
              <th>Contraseña</th>
              <th class="">Nombre</th>
              <th>Apellido paterno</th>
              <th>Apellido materno</th>
              <th>Correo electrónico</th>
              <th colspan="4"></th>
            </tr>
          </thead>

          <tbody>
            <% @supervisors.each do |supervisor| %>
              <tr>
                <td><%= supervisor.username %></td>
                <td><%= supervisor.internal_password %></td>
                <td class=""><%= supervisor.name %></td>
                <td><%= supervisor.first_last_name %></td>
                <td><%= supervisor.second_last_name %></td>
                <td><%= supervisor.email %></td>
                <td class=""><%= link_to 'Ver', supervisor %></td>
                <td class=""><%= link_to 'Editar', edit_supervisor_path(supervisor) %></td>
                <td class=""><%= link_to 'Borrar', supervisor, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar este curso de forma permanente?' } %></td>
                <td class=""><%= check_box_tag "supervisor_ids[]", supervisor.id, false, class: 'selectable' %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <%= submit_tag "Borrar seleccionados", :class => "buttond", data: { confirm: '¿Esta seguro que desea eliminar este curso de forma permanente?' } %>
      <% end %>


      <%= link_to destroy_all_supervisors_path,  method: :delete, :class => "buttond", data: { confirm: 'Esta Seguro?' } do %>
      Borrar Todos
      <% end %>

      <br>
      <%= link_to '+ Crear', new_supervisor_path, class: "btn btn-success"%>

      <br>
      <h3>Importar Excel</h3>

      <%= form_tag import_supervisors_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= button_tag type: 'submit', class: "button" do %>
                Subir CSV
            <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/supervisors/new.html.erb
<div class="content-container footer-container">
  <div class="container-fluid">
    <div class="jumbotron" >
      <h1>Nuevo Supervisor</h1>

      <%= render 'form', supervisor: @supervisor %>

      <%= link_to 'Atrás', supervisors_path %>

    </div>
  </div>
</div>

app/views/supervisors/show.html.erb
<div class="content-container footer-container">
  <div class="container-fluid">
    <div class="jumbotron" >

      <p id="notice"><%= notice %></p>

      <p>
        <strong>Nombre de usuario:</strong>
        <%= @supervisor.username %>
      </p>

      <p>
        <strong>Contraseña:</strong>
        <%= @supervisor.internal_password %>
      </p>

      <p>
        <strong>Nombre:</strong>
        <%= @supervisor.name %>
      </p>

      <p>
        <strong>Apellido paterno:</strong>
        <%= @supervisor.first_last_name %>
      </p>

      <p>
        <strong>Apellido materno:</strong>
        <%= @supervisor.second_last_name %>
      </p>

      <p>
        <strong>Correo electrónico:</strong>
        <%= @supervisor.email %>
      </p>

      <p>
        <strong>País:</strong>
        <%= @supervisor.country %>
      </p>

      <p>
        <strong>Estado:</strong>
        <%= @supervisor.state %>
      </p>

      <p>
        <strong>Ciudad:</strong>
        <%= @supervisor.city %>
      </p>

      <p>
        <strong>Socio:</strong>
        <%= @supervisor.partner %>
      </p>

      <p>
        <strong>Código de organización:</strong>
        <%= @supervisor.organization_code %>
      </p>

      <p>
        <strong>Género:</strong>
        <%= @supervisor.gender %>
      </p>

      <p>
        <strong>Fecha de nacimiento:</strong>
        <%= @supervisor.dob %>
      </p>

      <p>
        <strong>Número telefónico:</strong>
        <%= @supervisor.phone_number %>
      </p>

      <p>
        <strong>Idioma:</strong>
        <%= @supervisor.language %>
      </p>

      <%= link_to 'Editar', edit_supervisor_path(@supervisor) %> |
      <%= link_to 'Atrás', supervisors_path %>

    </div>
  </div>
</div>