config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root

      resources :tutors do
		      collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { get :export}

	    end

      resources :groups do
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { post :add_student}
          collection { delete :delete_student}
          collection { get :export}

          collection { delete :remove_students}
          collection { post :add_many_students}
	    end

      resources :supervisors do
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { post :import }
	    end

      resources :stakeholders do
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { post :import }
	    end

      resources :coordinators do
          collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}

	    end

      resources :students do
		      collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { get :export}
	    end

      resources :courses do
		      collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { get :export}

	    end

      get "/logout" => "devise/sessions#destroy"
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
      get "/login" => "devise/sessions#new"
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :course
  belongs_to :tutor
  belongs_to :supervisor

  has_and_belongs_to_many :students



  def self.add_student(group_id, student_id)
    group = Group.where(id: group_id).take
    student = Student.where(id: student_id).take

    group.students << student
  end

  def self.delete_student(group_id, student_id)

    sql = "DELETE FROM groups_students WHERE groups_students.student_id = #{student_id} AND groups_students.group_id = #{group_id}"
    ActiveRecord::Base.connection.execute(sql).to_a

  end



end

app/models/student.rb
class Student < ApplicationRecord
  has_and_belongs_to_many :courses
  has_and_belongs_to_many :groups

  def self.import(file)

    all_students = []
    Student.all.each do |student|
      all_students.push(student.username)
    end

    all_courses= {}
    Course.all.each do |course|
      all_courses[course.name] = course
    end

		xlsx = Roo::Spreadsheet.open(file.path)
    xlsx.drop(1).each do |row|

      username = row[0]
      if !all_students.include?(username)
        student = Student.create(
          username: row[0],
          internal_password: row[1],
          name: row[2],
          first_last_name: row[3],
          second_last_name: row[4],
          email: row[5],
          country: row[8],
          state: row[9],
          city: row[10],
          partner: row[7],
          organization_code: row[6],
          language: row[13],
          gender: row[21],
          dob: row[22],
          cca: row[11],
          promoter_name: row[23],
          promoter_email: row[24])

          all_students.push(username)

      else
          student = Student.where(username: username).take
      end


      courseName = row[17]

      student.courses << all_courses[courseName]


    end
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    if params[:search]
      @students = Student.where('name ILIKE ?', "%#{params[:search]}%").order("username ASC")
    else
      @students = Student.order("username ASC")
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  def import
   Student.import(params[:file])
   redirect_to students_path
  end

  # GET /students/1/edit
  def edit
  end

  def export
      @students = Student.all
    respond_to do |format|

      format.xlsx {render xlsx: 'export'}
      format.html
    end
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_multiple

    if params[:student_ids]
      Student.destroy(params[:student_ids])
      message = {notice: 'Preinsctito borrados con éxito.'}
    else
      message = {alert: 'Por favor selecciona al menos un Preinsctitos.'}
    end

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  def destroy_all
    Student.all.destroy_all

    redirect_to students_path, notice: "Preinsctitos Borrados Exitosamente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:username, :internal_password, :name, :first_last_name, :second_last_name, :email, :country, :state, :city, :partner, :organization_code, :gender, :dob, :phone_number, :language, :cca, :promoter_name, :promoter_email)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
      <%= form_with(model: student, local: true) do |form| %>
      <% if student.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

        <ul>
          <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>

      <div class="field">
        <%= form.label :username, 'Nombre de usuario' %>
        <%= form.text_field :username %>
      </div>

      <div class="field">
        <%= form.label :internal_password, 'Contraseña' %>
        <%= form.text_field :internal_password %>
      </div>

      <div class="field">
        <%= form.label :name, 'Nombre' %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :first_last_name, 'Apellido paterno' %>
        <%= form.text_field :first_last_name %>
      </div>

      <div class="field">
        <%= form.label :second_last_name, 'Apellido materno' %>
        <%= form.text_field :second_last_name %>
      </div>

      <div class="field">
        <%= form.label :email, 'Correo electrónico' %>
        <%= form.text_field :email %>
      </div>

      <div class="field">
        <%= form.label :country, 'País' %>
        <%= form.text_field :country %>
      </div>

      <div class="field">
        <%= form.label :state, 'Estado' %>
        <%= form.text_field :state %>
      </div>

      <div class="field">
        <%= form.label :city, 'Ciudad' %>
        <%= form.text_field :city %>
      </div>

      <div class="field">
        <%= form.label :partner, 'Socio' %>
        <%= form.text_field :partner %>
      </div>

      <div class="field">
        <%= form.label :organization_code, 'Código de organización' %>
        <%= form.text_field :organization_code %>
      </div>

      <div class="field">
        <%= form.label :gender, 'Género' %>
        <%= form.number_field :gender %>
      </div>

      <div class="field">
        <%= form.label :dob, 'Fecha de nacimiento' %>
        <%= form.date_select :dob, start_year: 1900 %>
      </div>

      <div class="field">
        <%= form.label :phone_number, 'Número telefónico' %>
        <%= form.text_field :phone_number %>
      </div>

      <div class="field">
        <%= form.label :language, 'Idioma' %>
        <%= form.text_field :language %>
      </div>

      <div class="field">
        <%= form.label :cca, 'CCA' %>
        <%= form.text_field :cca %>
      </div>

      <div class="field">
        <%= form.label :promoter_name, 'Promotor' %>
        <%= form.text_field :promoter_name %>
      </div>

      <div class="field">
        <%= form.label :promoter_email, 'Correo promotor' %>
        <%= form.text_field :promoter_email %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<div class="content-container footer-container">
  <div class="container-fluid">
    <div class="jumbotron" >
      <h1>Editar Preinscrito</h1>

      <%= render 'form', student: @student %>

      <%= link_to 'Ver', @student %> |
      <%= link_to 'Atrás', students_path %>

    </div>
  </div>
</div>

app/views/students/index.html.erb
<div class="content-container footer-container">
  <div class="container-fluid">
    <div class="jumbotron" >

      <h1>Preinscritos</h1>

      <div class="md-form mt-0">
        <%= form_tag(students_path, method: :get) do %>
          <%= text_field_tag :search,"", class: "form-control", placeholder: "Busqueda" %>
        <% end %>
      </div><br>

      <%= form_tag destroy_multiple_students_path, method: :delete do %>
      <div class="scroll">
        <table class="table table-hover table-fixed course_header fixed_header">
          <thead >
            <tr>
              <th>Nombre de usuario</th>
              <th>Contraseña</th>
              <th class="">Nombre</th>
              <th>Apellido paterno</th>
              <th>Apellido materno</th>
              <th>Correo electrónico</th>
              <th colspan="4"></th>
            </tr>
          </thead>


            <tbody>
              <% @students.each do |student| %>
                <tr>
                  <td><%= student.username %></td>
                  <td><%= student.internal_password %></td>
                  <td class=""><%= student.name %></td>
                  <td><%= student.first_last_name %></td>
                  <td><%= student.second_last_name %></td>
                  <td><%= student.email %></td>
                  <td class=""><%= link_to 'Ver', student %></td>
                  <td class=""><%= link_to 'Editar', edit_student_path(student) %></td>
                  <td class=""><%= link_to 'Borrar', student, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar este curso de forma permanente?' } %></td>
                  <td class=""><%= check_box_tag "student_ids[]", student.id, false, class: 'selectable' %></td>
                </tr>
              <% end %>
            </tbody>
        </table>
      </div>


      <%= submit_tag "Borrar seleccionados", :class => "buttond", data: { confirm: '¿Esta seguro que desea eliminar este curso de forma permanente?' } %>
      <% end %>

      <%= link_to destroy_all_students_path,  method: :delete, :class => "buttond", data: { confirm: 'Esta Seguro?' } do %>
      Borrar Todos
      <% end %>

      <br>
      <h3>Importar Excel</h3>

      <%= form_tag import_students_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= button_tag type: 'submit', class: "button" do %>
                Subir CSV
            <% end %>
      <% end %>


      <%= link_to '+ Crear', new_student_path, class: "btn btn-success"%>
      <%= link_to 'Download spreadsheet', export_students_path(format: :xlsx) %>
    </div>
  </div>
</div>

app/views/students/new.html.erb
<div class="content-container footer-container">
  <div class="container-fluid">
    <div class="jumbotron" >
      <h1>Nuevo preinscrito</h1>

      <%= render 'form', student: @student %>

      <%= link_to 'Atrás', students_path %>

    </div>
  </div>
</div>

app/views/students/show.html.erb
<div class="content-container footer-container">
  <div class="container-fluid">
    <div class="jumbotron" >
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Nombre de usuario:</strong>
        <%= @student.username %>
      </p>

      <p>
        <strong>Contraseña:</strong>
        <%= @student.internal_password %>
      </p>

      <p>
        <strong>Nombre:</strong>
        <%= @student.name %>
      </p>

      <p>
        <strong>Apellido paterno:</strong>
        <%= @student.first_last_name %>
      </p>

      <p>
        <strong>Apellido materno:</strong>
        <%= @student.second_last_name %>
      </p>

      <p>
        <strong>Correo electrónico:</strong>
        <%= @student.email %>
      </p>

      <p>
        <strong>País:</strong>
        <%= @student.country %>
      </p>

      <p>
        <strong>Estado:</strong>
        <%= @student.state %>
      </p>

      <p>
        <strong>Ciudad:</strong>
        <%= @student.city %>
      </p>

      <p>
        <strong>Socio:</strong>
        <%= @student.partner %>
      </p>

      <p>
        <strong>Código de organización:</strong>
        <%= @student.organization_code %>
      </p>

      <p>
        <strong>Género:</strong>
        <%= @student.gender %>
      </p>

      <p>
        <strong>Fecha de nacimiento:</strong>
        <%= @student.dob %>
      </p>

      <p>
        <strong>Número telefónico:</strong>
        <%= @student.phone_number %>
      </p>

      <p>
        <strong>Idioma:</strong>
        <%= @student.language %>
      </p>

      <p>
        <strong>CCA:</strong>
        <%= @student.cca %>
      </p>

      <p>
        <strong>Promotor:</strong>
        <%= @student.promoter_name %>
      </p>

      <p>
        <strong>Correo de promotor:</strong>
        <%= @student.promoter_email %>
      </p>

      <%= link_to 'Editar', edit_student_path(@student) %> |
      <%= link_to 'Atrás', students_path %>

    </div>
  </div>
</div>