config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root

      resources :tutors do
		      collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { get :export}

	    end

      resources :groups do
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { post :add_student}
          collection { delete :delete_student}
          collection { get :export}

          collection { delete :remove_students}
          collection { post :add_many_students}
	    end

      resources :supervisors do
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { post :import }
	    end

      resources :stakeholders do
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { post :import }
	    end

      resources :coordinators do
          collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}

	    end

      resources :students do
		      collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { get :export}
	    end

      resources :courses do
		      collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { get :export}

	    end

      get "/logout" => "devise/sessions#destroy"
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
      get "/login" => "devise/sessions#new"
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :course
  belongs_to :tutor
  belongs_to :supervisor

  has_and_belongs_to_many :students



  def self.add_student(group_id, student_id)
    group = Group.where(id: group_id).take
    student = Student.where(id: student_id).take

    group.students << student
  end

  def self.delete_student(group_id, student_id)

    sql = "DELETE FROM groups_students WHERE groups_students.student_id = #{student_id} AND groups_students.group_id = #{group_id}"
    ActiveRecord::Base.connection.execute(sql).to_a

  end



end

app/models/tutor.rb
class Tutor < ApplicationRecord
  has_many :groups, dependent: :destroy

  def self.import(file)
    o = [('a'..'z'), ('A'..'Z'), ('0'..'9')].map(&:to_a).flatten

    all_tutors = []
    Tutor.all.each do |tutor|
      all_tutors.push(tutor.username)
    end


		xlsx = Roo::Spreadsheet.open(file.path)
    xlsx.drop(1).each do |row|

      username = row[0]

      if !all_tutors.include?(username)
        str = (0...6).map { o[rand(o.length)] }.join
        Tutor.create(
          username: row[0],
          internal_password: str,
          name: row[1],
          first_last_name: row[2],
          second_last_name: row[3],
          email: row[4],
          country: row[8],
          state: row[9],
          city: row[10],
          partner: row[6],
          organization_code: row[7])

          all_tutors.push(username)
      end


    end
	end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index

    if params[:course_id]
      @groups = Group.where(course_id: params[:course_id])


    else
      @groups = Group.all

    end

    @courses = Course.order("start_date DESC", "name")
  end

  # GET /groups/1
  # GET /groups/1.json
  def show

      @not_ins = []
      @ins = []

      @group.course.students.each do |student|
        @not_ins.push(student)
      end

      Group.where(course_id: @group.course.id).each do |group|
        group.students.each do |student|
          @ins.push(student)
        end
      end

      @result = @not_ins - @ins

  end

  # GET /groups/new
  def new
    @group = Group.new
    @course = Course.all.where(id: params[:course_id]).take

    last_group = Group.where(course_id: params[:course_id]).last
    if last_group == nil
      @group_num = 1
    else
      @group_num = last_group.group_number + 1
    end



    tutors_ins = []
    tutors_not_ins = []

     Tutor.all.order("organization_code").each do |tutor|
       tutors_not_ins.push(tutor)
     end

    Group.all.each do |group|
      tutors_ins.push(group.tutor)
    end


    @tutors = (tutors_not_ins - tutors_ins)

    @supervisors = Supervisor.all

  end

  # GET /groups/1/edit
  def edit

    @group_num = @group.group_number

    tutors_ins = []
    tutors_not_ins = []

     Tutor.all.order("organization_code").each do |tutor|
       tutors_not_ins.push(tutor)
     end

    Group.all.each do |group|
      tutors_ins.push(group.tutor)
    end


    @tutors = [@group.tutor] + (tutors_not_ins - tutors_ins)

    @supervisors = [@group.supervisor] + Supervisor.all
  end

  def export
    @groups = Group.where(course_id: params[:course_id])
    @coordinator = Coordinator.all.take
    @stakeholders = Stakeholder.all.take

    respond_to do |format|

      format.xlsx {render xlsx: 'export'}
      format.html
    end
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_student
    Group.add_student(params[:group], params[:student])
    redirect_to "#{groups_path}/#{params[:group]}"

  end

  def add_many_students
    if params[:student_ids]
      params[:student_ids].each do |student|
        Group.add_student(params[:group], student)
      end
    end

    redirect_to "#{groups_path}/#{params[:group]}"

  end

  def delete_student
    Group.delete_student(params[:group], params[:student])
    redirect_to "#{groups_path}/#{params[:group]}"

  end

  def remove_students
    if params[:student_ids]
      params[:student_ids].each do |student|
        Group.delete_student(params[:group], student)
      end
    end

    redirect_to "#{groups_path}/#{params[:group]}"

  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_multiple

    if params[:group_ids]
      Group.destroy(params[:group_ids])
      message = {notice: 'Borrado con éxito.'}
    else
      message = {alert: 'Por favor selecciona al menos uno.'}
    end

    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  def destroy_all
    Group.all.each do  |group|
      group.destroy
    end

    redirect_to groups_path, notice: "Borrados Exitosamente"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:group_number, :course_id, :tutor_id, :supervisor_id)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :group_number, 'Número de grupo' %>
    <%= form.number_field :group_number, value: @group_num%>
  </div>

  <%  if params[:course_id] %>

    <div class="field">
      <%= form.label :course_id, "#{@course.name}" %>

      <%= form.text_field :course_id, value: params[:course_id]  %>

    </div>

  <% else %>

    <div class="field">
      <%= form.label :course_id, 'Curso' %>
      <%= form.text_field :course_id %>
    </div>

  <% end %>



  <div class="field">
    <%= form.label :tutor_id, 'Tutor' %>
    <%= select("group", "tutor_id", @tutors.collect {|tutor| [ "#{tutor.organization_code} __________ #{tutor.name} #{tutor.first_last_name}  #{tutor.second_last_name}", tutor.id ] })%>
  </div>

  <div class="field">
    <%= form.label :supervisor_id, 'Supervisor' %>
    <%= select("group", "supervisor_id", @supervisors.collect {|supervisor| [ "#{supervisor.organization_code} __________ #{supervisor.name} #{supervisor.first_last_name}  #{supervisor.second_last_name}", supervisor.id ] })%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="content-container footer-container">
  <div class="container-fluid">
    <div class="jumbotron" >
      <h1>Editar Groupo</h1>

      <%= render 'form', group: @group %>

      <%= link_to 'Ver', @group %> |
      <%= link_to 'Atrás', groups_path %>


    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="content-container footer-container">
  <div class="container-fluid">
    <div class="jumbotron" >

      <p id="notice"><%= notice %></p>


      <h1>Groups</h1>

      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Seleccionar Curso
        </button>
        <div class="dropdown-menu scroll" aria-labelledby="dropdownMenuButton">


          <%= link_to "Todos",  groups_url,  class: "dropdown-item" %>
          <% @courses.each do |course| %>

            <%= link_to "#{course.start_date} #{course.name}",  {:course_id => course.id},  class: "dropdown-item" %>

          <% end %>

        </div>
      </div>

      <%= form_tag destroy_multiple_groups_path, method: :delete do %>

      <div class="scroll">
        <table class="table table-hover table-fixed course_header">

          <!--Table head-->
          <thead>
            <tr>
              <th>Course</th>
              <th>Group number</th>
              <th>Tutor</th>
              <th>Supervisor</th>
              <th colspan="4"></th>
            </tr>
          </thead>

          <tbody>
            <% @groups.each do |group| %>
            <tr>
              <td><%= group.course.name %></td>
              <td><%= group.group_number %></td>
              <td><%= group.tutor.name %></td>
              <td><%= group.supervisor.name %></td>
              <td><%= link_to 'Ver', group %></td>
              <td><%= link_to 'Editar', edit_group_path(group) %></td>
              <td><%= link_to 'Eliminar', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td class=""><%= check_box_tag "group_ids[]", group.id, false, class: 'selectable' %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>

      <br>



      <%= submit_tag "Borrar seleccionados", :class => "btn", data: { confirm: '¿Esta seguro que desea eliminar este curso de forma permanente?' } %>

      <% end %>

      <br>
      <%  if params[:course_id] %>

      <%= link_to 'Nuevo Grupo', new_group_path(course_id: params[:course_id]), class: "btn "  %>

        <% if @groups.take != nil %>

        <%= link_to 'Descargar Excel', export_groups_path(format: :xlsx, course_id: @groups.take.course.id), class: "btn" %>

        <% end %>

      <% end %>











    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="content-container footer-container">
  <div class="container-fluid">
    <div class="jumbotron" >

      <h1>Nuevo grupo</h1>

      <%= render 'form', group: @group %>

      <%= link_to 'Atrás', groups_path %>


    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="content-container footer-container">
  <div class="container-fluid">
    <div class="jumbotron" >

      <p id="notice"><%= notice %></p>

      <h3><%= @group.course.name %></h3>
      <h3>Grupo: <%= @group.group_number %></h3> <br>

      <h2>Partcipantes Inscritos</h2>
      <%= form_tag remove_students_groups_path(group: @group), method: :delete do %>
      <div class="scroll">
          <table class="table table-hover table-fixed">
            <thead >
              <tr>
                <th>Nombre de estudiante</th>
                <th>Apellido paterno</th>
                <th>Apellido materno</th>
                <th>CCA</th>
                <th>Nombre de promotor</th>
                <th>Correo promotor</th>
                <th>Aliado</th>
                <th>País</th>
              </tr>
            </thead>

            <% @group.students.each do |student| %>
              <tbody>
              <tr>
                <td><%= student.name %></td>
                <td><%= student.first_last_name %></td>
                <td><%= student.second_last_name %></td>
                <td><%= student.cca %></td>
                <td><%= student.promoter_name %></td>
                <td><%= student.promoter_email %></td>
                <td><%= student.partner %></td>
                <td><%= student.country %></td>

                <td>
                  <%= link_to delete_student_groups_path(group: @group, student: student),  method: :delete, :class => "buttond", data: { confirm: 'Esta Seguro?' }, class: "btn btn-sm" do %>
                  Borrar
                  <% end %>
                </td>

                <td class=""><%= check_box_tag "student_ids[]", student.id, false, class: 'selectable' %></td>

              </tr>
            </tbody>
            <% end %>
          </table>


      </div>
      <br>
      <%= submit_tag "Borrar seleccionados", :class => "btn", data: { confirm: '¿Esta seguro que desea eliminar este curso de forma permanente?' } %>
      <% end %>
      <br>

      <h2>Partcipantes No Inscritos</h2>
        <%= form_tag add_many_students_groups_path(group: @group), method: :post do %>
        <div class="scroll">
          <table class="table table-hover table-fixed">
              <thead >
                <tr>
                  <th>Nombre de estudiante</th>
                  <th>Apellido paterno</th>
                  <th>Apellido materno</th>
                  <th>CCA</th>
                  <th>Nombre de promotor</th>
                  <th>Correo promotor</th>
                  <th>Aliado</th>
                  <th>País</th>
                </tr>
              </thead>

              <% @result.each do |student| %>
              <tbody>
              <tr>
                <td><%= student.name %></td>
                <td><%= student.first_last_name %></td>
                <td><%= student.second_last_name %></td>
                <td><%= student.cca %></td>
                <td><%= student.promoter_name %></td>
                <td><%= student.promoter_email %></td>
                <td><%= student.partner %></td>
                <td><%= student.country %></td>
                <td>
                  <%= form_tag add_student_groups_path(group: @group, student: student) do %>
                  <%= button_tag type: 'submit', class: "btn btn-sm" do %>
                  Agregar
                  <% end %>
                <% end %>
                </td>

                <td class=""><%= check_box_tag "student_ids[]", student.id, false, class: 'selectable' %></td>

              </tr>
            </tbody>
            <% end %>
          </table>
        </div>

        <br>

        <%= submit_tag "Agregar seleccionados", :class => "btn", data: { confirm: '¿Desea Continuar?' } %>
        <% end %>
        <br>


      <%= link_to 'Regresar', groups_path, class: "btn"%>

    </div>
  </div>
</div>