config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root

      resources :tutors do
		      collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { get :export}

	    end

      resources :groups do
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { post :add_student}
          collection { delete :delete_student}
          collection { get :export}

          collection { delete :remove_students}
          collection { post :add_many_students}
	    end

      resources :supervisors do
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { post :import }
	    end

      resources :stakeholders do
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { post :import }
	    end

      resources :coordinators do
          collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}

	    end

      resources :students do
		      collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { get :export}
	    end

      resources :courses do
		      collection { post :import }
		      collection { delete :destroy_multiple }
          collection { delete :destroy_all}
          collection { get :export}

	    end

      get "/logout" => "devise/sessions#destroy"
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
      get "/login" => "devise/sessions#new"
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TutorVirtual2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% unless !(user_signed_in?) %>
      <div class="sidebar-container">

        <div class="sidebar-logo">
          <%= image_tag "logo.png"%>
          <h5 class="username">Bienvenido <%= current_user.email %>!</h5>
        </div>

        <ul class="sidebar-navigation">

          <li><%= link_to home_index_url do %> Inicio <% end %></li>
          <li><%= link_to courses_url do %> Cursos <% end %></li>
          <li><%= link_to tutors_url do %> Tutores <% end %></li>
          <li><%= link_to students_url do %> Preinscritos <% end %></li>
          <li><%= link_to coordinators_url do %> Coordinadores <% end %></li>
          <li><%= link_to supervisors_url do %> Supervisores <% end %></li>
          <li><%= link_to stakeholders_url do %> Administradores <% end %></li>
          <li><%= link_to groups_url do %> Grupos <% end %></li>
          <li><%= link_to logout_url do %> Cerrar Sesión <% end %></li>

        </ul>
      </div>
    <% end %>


    <%= yield %>
  </body>
</html>